package com.mi.onextbox.lsp

import android.app.Service
import android.content.Context
import android.view.Display
import com.mi.onextbox.lsp.LspConfig.KeyguardFeature
import com.mi.onextbox.lsp.compat.ModernHookRegistry
import com.mi.onextbox.lsp.compat.ModernHookRuntime
import com.mi.onextbox.lsp.compat.ModernReflect as Reflect
import io.github.libxposed.api.XposedInterface
import java.lang.reflect.Modifier
import java.util.concurrent.atomic.AtomicBoolean

/** Only relax the stock screenshot app's screen-on gate during a hardware-key AOD capture. */
internal object AodScreenshotHooker {
    private const val TAG = "ONextBox-Capture"

    private fun enabled() = LspConfig.isKeyguardFeatureEnabledXposed(KeyguardFeature.AodScreenshot)

    fun hook(loader: ClassLoader) {
        if (!enabled()) return
        runCatching { install(loader) }
            .onSuccess { HookLog.i(TAG, "Installed screenshot-service AOD capture gate") }
            .onFailure { HookLog.w(TAG, "Unavailable screenshot-service AOD gate, stock handling retained", it) }
    }

    private fun install(loader: ClassLoader) {
        val requestClass = Reflect.findClass("com.oplus.screenshot.common.core.ScreenshotRequest", loader)
        val captureClass = Reflect.findClass("com.oplus.screenshot.screenshot.task.TaskCapture", loader)
        val screenUtil = Reflect.findClass("com.oplus.screenshot.common.utils.l", loader)
        // Use real DEX names, not the getter aliases generated by decompilers.
        // Validate the full C17 contract before installing either hook, fail closed on other APKs.
        val sourceGetter = requestClass.getDeclaredMethod("V").apply { isAccessible = true }
        val contextGetter = requestClass.getDeclaredMethod("o").apply { isAccessible = true }
        val displayGetter = requestClass.getDeclaredMethod("t").apply { isAccessible = true }
        val execute = captureClass.getDeclaredMethod("e", requestClass)
        val screenOn = screenUtil.getDeclaredMethod("a", Context::class.java)
        check(sourceGetter.returnType == String::class.java &&
            contextGetter.returnType == Service::class.java &&
            displayGetter.returnType == Display::class.java &&
            listOf(sourceGetter, contextGetter, displayGetter, execute).none { Modifier.isStatic(it.modifiers) } &&
            execute.returnType == Void.TYPE && Modifier.isStatic(screenOn.modifiers) &&
            screenOn.returnType == Boolean::class.javaPrimitiveType) { "Unknown C17 screenshot contract" }

        val scope = CaptureRequestScope<AodRequest>()
        val logged = AtomicBoolean()
        // ScreenUtil is small enough to be AOT-inlined, deoptimize only its verified caller.
        if (!ModernHookRuntime.requireModule().deoptimize(execute)) {
            HookLog.w(TAG, "AOD capture caller deoptimization unavailable")
        }
        ModernHookRegistry.installFast(
            "capture:aod-service:" + screenOn.toGenericString(), screenOn, XposedInterface.Hooker { chain ->
                val stock = chain.proceed()
                val active = scope.get()
                // Never change PowerManager globally, nor the later preview's screen-off handling.
                if (stock == false && active != null && chain.getArg(0) === active.context && active.allowed()) {
                    if (logged.compareAndSet(false, true)) {
                        HookLog.i(TAG, "Allowed hardware-key AOD capture, stock security and save pipeline retained")
                    }
                    true
                } else stock
            },
        )
        ModernHookRegistry.installFast(
            "capture:aod-service:" + execute.toGenericString(), execute, XposedInterface.Hooker { chain ->
                val active = runCatching {
                    val request = chain.getArg(0) ?: return@runCatching null
                    val source = sourceGetter.invoke(request) as? String
                    val context = contextGetter.invoke(request) as? Context ?: return@runCatching null
                    val display = displayGetter.invoke(request) as? Display ?: return@runCatching null
                    AodRequest(context, display, source).takeIf { it.allowed() }
                }.getOrNull()
                scope.withValue(active) { chain.proceed() }
            },
        )
        // TaskCapture still runs its original window/user/enterprise checks and native capture.
        // Its normal path schedules saving before the main-thread preview callback, whose stock
        // screen-off cleanup waits for saving/storage to finish, no fake ON state is needed there.
    }

    private data class AodRequest(val context: Context, val display: Display, val source: String?) {
        fun allowed(): Boolean = runCatching {
            KeyguardCaptureRules.allowAodScreenshot(
                enabled(), context.packageName, source, display.displayId, display.state,
            )
        }.getOrDefault(false)
    }
}
